"""Split a splat into the per-link robot assets PolaRiS draws the robot from.

The classifier is SplatSim's (github.com/qureshinomaan/SplatSim,
`scripts/articulated_robot_pipeline.py`): points sampled on one link at a time carry that
link's label, a `KNeighborsClassifier(n_neighbors=10)` is fitted on them, and it then says
which link each gaussian belongs to. SplatSim samples the visible link by rendering depth
in PyBullet; we sample the USD meshes of the articulation PolaRiS evaluates with, posed at
the configuration `solve_capture_qpos.py` recovered.

What comes out matches the official `nvidia_droid/SEGMENTED` assets exactly:

  one ply per mesh prim, named after the prim path with slashes turned into dashes,
  holding that prim's gaussians in the prim's own frame, in metres.

Verified against the shipped assets: the 19 names we enumerate are identical to theirs,
their link plys are 3DGS and their gripper plys are 2DGS (PolaRiS's loader takes the first
two scales either way), and `SplatRenderer.transform_many` rotates positions and gaussian
rotations but passes the higher-order spherical harmonics through untouched — so this
writes positions and rotations in the link frame and leaves the harmonics alone, exactly
as the official assets do.

Gaussians too far from every link surface are left in the scene: they are cables, the
mounting plate and background that the arm mask happened to cover.

With `--semantics` the "is this the robot" question is answered by GSWorld's own
per-gaussian link labels instead of by distance (their `*_semantics_gs.npy`, generated by
`gsworld/real2sim/scripts/uniform_pcd_from_urdf_visual_mesh.py` at their
`robot_scan_qpos`), and the KNN is only asked which prim it belongs to, because the prim
frames are what PolaRiS moves at run time. Labelled gaussians that sit further than
`--semantic-max-distance` from every posed link surface are dropped rather than kept:
they are reconstruction ghosts of the arm, and leaving them in the scene would put a
second arm on the table.
"""

import argparse

from isaaclab.app import AppLauncher

parser = argparse.ArgumentParser()
parser.add_argument("--environment", default="DROID-PourMustard")
parser.add_argument("--splat", required=True, help="scene splat that still contains the arm")
parser.add_argument("--qpos", required=True, help="npy from solve_capture_qpos.py")
parser.add_argument("--arm-points", default=None,
                    help="optional npy of arm points, only used to report coverage")
parser.add_argument("--max-distance", type=float, default=0.035,
                    help="a gaussian further than this from every link surface stays in the scene")
parser.add_argument("--max-distance-high", type=float, default=0.08,
                    help="the same limit above --high-z, where it can be looser: up there the "
                         "only thing that sits centimetres off a link is hardware bolted to it, "
                         "the wrist camera and its bracket and the cable runs, all of which move "
                         "with the link and belong to it. Near the table the tight limit stays, "
                         "or the cloth around the base would be claimed as robot.")
parser.add_argument("--high-z", type=float, default=0.15,
                    help="metres above the robot base frame, so well clear of the table")
parser.add_argument("--semantics", default=None,
                    help="GSWorld per-gaussian link labels; -1 is scene, >=1 is the robot. "
                         "When given, these decide what is robot and the distance limits "
                         "above are not used for that decision.")
parser.add_argument("--semantic-max-distance", type=float, default=0.12,
                    help="a labelled gaussian further than this from every posed link "
                         "surface is a ghost of the arm and is dropped")
parser.add_argument("--samples-per-mesh", type=int, default=6000)
parser.add_argument("--neighbours", type=int, default=10, help="SplatSim uses 10")
parser.add_argument("--out-dir", required=True, help="written like nvidia_droid/SEGMENTED")
parser.add_argument("--scene-out", required=True, help="the splat with the robot removed")
parser.add_argument("--report", required=True)
args_cli, _ = parser.parse_known_args()
args_cli.headless = True
args_cli.enable_cameras = True
app_launcher = AppLauncher(args_cli)
simulation_app = app_launcher.app

import json  # noqa: E402
from pathlib import Path  # noqa: E402

import gymnasium as gym  # noqa: E402
import numpy as np  # noqa: E402
import torch  # noqa: E402
from isaaclab_tasks.utils import parse_env_cfg  # noqa: E402
from plyfile import PlyData, PlyElement  # noqa: E402
from scipy.spatial import cKDTree  # noqa: E402
from sklearn.neighbors import KNeighborsClassifier  # noqa: E402

import r2s2r.environments  # noqa: E402,F401
from r2s2r.robot_links import body_frames, collect_meshes, quat_to_mat  # noqa: E402


def quat_mul(a, b):
    w1, x1, y1, z1 = a
    w2, x2, y2, z2 = b.T
    return np.stack([
        w1 * w2 - x1 * x2 - y1 * y2 - z1 * z2,
        w1 * x2 + x1 * w2 + y1 * z2 - z1 * y2,
        w1 * y2 - x1 * z2 + y1 * w2 + z1 * x2,
        w1 * z2 + x1 * y2 - y1 * x2 + z1 * w2], axis=1)


def mat_to_quat(r):
    t = np.trace(r)
    if t > 0:
        s = np.sqrt(t + 1.0) * 2
        q = [0.25 * s, (r[2, 1] - r[1, 2]) / s, (r[0, 2] - r[2, 0]) / s, (r[1, 0] - r[0, 1]) / s]
    elif r[0, 0] > r[1, 1] and r[0, 0] > r[2, 2]:
        s = np.sqrt(1 + r[0, 0] - r[1, 1] - r[2, 2]) * 2
        q = [(r[2, 1] - r[1, 2]) / s, 0.25 * s, (r[0, 1] + r[1, 0]) / s, (r[0, 2] + r[2, 0]) / s]
    elif r[1, 1] > r[2, 2]:
        s = np.sqrt(1 + r[1, 1] - r[0, 0] - r[2, 2]) * 2
        q = [(r[0, 2] - r[2, 0]) / s, (r[0, 1] + r[1, 0]) / s, 0.25 * s, (r[1, 2] + r[2, 1]) / s]
    else:
        s = np.sqrt(1 + r[2, 2] - r[0, 0] - r[1, 1]) * 2
        q = [(r[1, 0] - r[0, 1]) / s, (r[0, 2] + r[2, 0]) / s, (r[1, 2] + r[2, 1]) / s, 0.25 * s]
    q = np.array(q)
    return q / np.linalg.norm(q)


def main():
    report = {}
    qpos = np.load(args_cli.qpos)
    report["qpos"] = [float(v) for v in qpos]

    env_cfg = parse_env_cfg(args_cli.environment, device="cuda", num_envs=1, use_fabric=True)
    env = gym.make(args_cli.environment, cfg=env_cfg)
    env.reset()
    u = env.unwrapped
    robot = u.scene["robot"]
    names = list(robot.data.joint_names)
    arm_ids = [names.index(f"panda_joint{i + 1}") for i in range(7)]
    t = torch.tensor(qpos, dtype=torch.float32, device=u.device)[None]
    robot.write_joint_state_to_sim(t, torch.zeros_like(t), joint_ids=arm_ids)
    u.sim.render()
    u.scene.update(0)

    meshes = collect_meshes(u.sim.stage, robot, samples=args_cli.samples_per_mesh)
    pos, rot = body_frames(robot)
    base_i = robot.data.body_names.index("panda_link0")
    bp, br = pos[base_i], rot[base_i]

    # every mesh's samples and its own frame, both in the robot base frame
    train_pts, train_lab, frames = [], [], []
    for k, m in enumerate(meshes):
        world = m["points"] @ rot[m["body"]].T + pos[m["body"]]
        train_pts.append((world - bp) @ br)
        train_lab.append(np.full(len(m["points"]), k))
        # Prim frame = body frame composed with the static mesh-to-body transform, with the
        # scale divided out. The Panda geometry prims carry a 0.01 scale (their meshes are
        # authored in centimetres), but at run time PolaRiS moves a link splat by the
        # prim's position and quaternion only — `GeometryPrim.get_world_poses` returns no
        # scale and `transform_many` applies none. The official assets match: their link
        # plys measure 0.1 to 0.3 m, so they are metric with the prim's rotation.
        r_mesh = m["mesh_in_body"][:3, :3]
        r_mesh = r_mesh / np.linalg.norm(r_mesh, axis=0, keepdims=True)
        r_world = rot[m["body"]] @ r_mesh
        t_world = rot[m["body"]] @ m["mesh_in_body"][:3, 3] + pos[m["body"]]
        frames.append({"rot": br.T @ r_world, "pos": (t_world - bp) @ br})
    train_pts = np.concatenate(train_pts)
    train_lab = np.concatenate(train_lab)
    report["meshes"] = len(meshes)
    report["training_points"] = int(len(train_pts))

    knn = KNeighborsClassifier(n_neighbors=args_cli.neighbours)
    knn.fit(train_pts, train_lab)
    surface = cKDTree(train_pts)

    ply = PlyData.read(args_cli.splat)
    vert = ply["vertex"]
    xyz = np.stack([vert["x"], vert["y"], vert["z"]], axis=1).astype(np.float64)
    dist, _ = surface.query(xyz)
    report["gaussians"] = int(len(xyz))
    dropped = np.zeros(len(xyz), bool)
    if args_cli.semantics:
        sem = np.load(args_cli.semantics)
        if len(sem) != len(xyz):
            raise SystemExit(f"{len(sem)} labels for {len(xyz)} gaussians")
        labelled = sem >= 1
        on_robot = labelled & (dist < args_cli.semantic_max_distance)
        dropped = labelled & ~on_robot
        report["labelled_robot"] = int(labelled.sum())
        report["dropped_ghosts"] = int(dropped.sum())
        report["label_distance_percentiles_mm"] = [
            float(np.percentile(dist[labelled], q) * 1000) for q in (50, 90, 99)]
    else:
        limit = np.where(xyz[:, 2] > args_cli.high_z,
                         args_cli.max_distance_high, args_cli.max_distance)
        on_robot = dist < limit
    report["on_robot"] = int(on_robot.sum())
    report["on_robot_within_tight_limit"] = int((dist < args_cli.max_distance).sum())

    labels = np.full(len(xyz), -1)
    labels[on_robot] = knn.predict(xyz[on_robot])

    rot_names = sorted([p.name for p in vert.properties if p.name.startswith("rot_")],
                       key=lambda s: int(s.split("_")[-1]))
    quats = np.stack([vert[n] for n in rot_names], axis=1).astype(np.float64)
    quats /= np.linalg.norm(quats, axis=1, keepdims=True)

    out_dir = Path(args_cli.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for k, m in enumerate(meshes):
        sel = labels == k
        if sel.sum() < 50:
            written.append({"name": m["name"], "gaussians": int(sel.sum()), "written": False})
            continue
        f = frames[k]
        local_xyz = (xyz[sel] - f["pos"]) @ f["rot"]
        q_inv = mat_to_quat(f["rot"].T)
        local_q = quat_mul(q_inv, quats[sel])
        data = vert.data[sel].copy()
        data["x"], data["y"], data["z"] = local_xyz[:, 0], local_xyz[:, 1], local_xyz[:, 2]
        for i, n in enumerate(rot_names):
            data[n] = local_q[:, i]
        span = local_xyz.max(0) - local_xyz.min(0)
        if span.max() < 0.01 or span.max() > 1.0:
            raise SystemExit(
                f"{m['name']} spans {np.round(span, 4)} m in its own frame; the official "
                "link assets measure 0.02 to 0.3 m, so the frame carries a stray scale")
        PlyData([PlyElement.describe(data, "vertex")]).write(out_dir / f"{m['name']}.ply")
        written.append({"name": m["name"], "gaussians": int(sel.sum()), "written": True,
                        "extent_m": [float(v) for v in span]})
    report["links"] = written

    keep = (labels < 0) & ~dropped
    PlyData([PlyElement.describe(vert.data[keep], "vertex")]).write(args_cli.scene_out)
    report["scene_gaussians_left"] = int(keep.sum())
    if args_cli.semantics:
        np.save(str(Path(args_cli.scene_out).with_suffix("")) + "_semantics.npy",
                np.load(args_cli.semantics)[keep])

    if args_cli.arm_points:
        arm = np.load(args_cli.arm_points)
        d, _ = surface.query(arm)
        report["arm_points_within_max_distance"] = float((d < args_cli.max_distance).mean())
        high = arm[:, 2] > args_cli.high_z
        report["arm_points_claimed"] = float(np.mean(np.where(
            high, d < args_cli.max_distance_high, d < args_cli.max_distance)))

    with open(args_cli.report, "w") as f:
        json.dump(report, f, indent=1)
    env.close()


if __name__ == "__main__":
    main()
    simulation_app.close()
